### ISSUE TITLE
Does this work with non Cloud9 generated boxes? (ie. over ssh)

### ISSUE THREAD

**Issue by marcato15** [michaelmitchell/c9.ide.language.javascript.eslintd#3]
I have a pretty vanilla Ubuntu 16.04 box I'm using with Cloud 9 over ssh. I went through your installation and then setup one of my projects as the root directory in a cloud 9 environment. However, I'm still getting complaints about plugins not being installed even though I've run yarn install in my project root, and when I run ```~/.c9/node_modules/.bin/eslint_d  src/components/molecules/Accordion/Accordion.jsx ``` from the project root it's still giving me ```Definition for rule 'import / no - extraneous - dependencies' was not found  import / no - extraneous - dependencies```

**Comment by michaelmitchell** [comment]
This sounds like more of a problem with your eslint config rather than this plugin, if you are seeing that report from eslint then the plugin is function correctly but a linting error was found which in your case is related to this eslint plugin https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-extraneous-dependencies.md

If the documents for eslint-plugin-import do not help you solve your linting error or you believe there is an error with eslint-plugin-import you should report it there, alternatively you could disable eslint-plugin-import in your eslintrc

**Comment by marcato15** [comment]
Thanks. I removed that plugin for now just to make sure the other stuff would work. When I run the command ```~/.c9/node_modules/.bin/eslint_d src/components/molecules/Accordion/Accordion.jsx``` now I'm getting all the right errors, but they are not showing up in the editor.  Do I have to turn any settings on in my project settings for the eslint_d errors to show up?

**Comment by marcato15** [comment]
Also, if I install a plugin in my project's `node_modules` directory, will `eslint_d` be able to have access to that plugin?

**Comment by marcato15** [comment]
So, I realized this was using a global parser and I was looking for a local one, so I just wrote my own parser, but used your plugin as a jumping off point. Thanks!

**Comment by michaelmitchell** [comment]
Yes, eslint_d should access plugins from your projects node_modules no problem.
